version: '3'
services:
  discovery:
    build: .
    container_name: discovery
    hostname: discovery
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/DjangoFiles # For dev
      - ./database:/DjangoFiles/database
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.discovery.tls.certresolver=myresolver
      - traefik.http.routers.discovery.rule=Host(`$DOMAIN`)
      - traefik.http.services.discovery.loadbalancer.server.port=8000

#    command: "bash launch.sh"
    command: "sleep infinity" # for dev


networks:
  frontend:
    external: true


